### ISSUE TITLE
Low fidelity( Password reset)

### ISSUE THREAD

**Issue by Luccchyyyy** [zuri-training/colflix_team117#42]

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A9807

This is the link to Password Reset screen 2 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A9844

This is the link to Password Reset screen 3 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A9883

This is the link to Password Reset screen 4 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A9926

This is the link to Password Reset screen 5 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A9972

This is the link to Password Reset screen 6 which I worked on

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A10050

This is the link to Password Reset screen 7 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A10130

This is the link to the Success screen for Password Reset which I worked.
