### ISSUE TITLE
Low fidelty(Sign in page)

### ISSUE THREAD

**Issue by Luccchyyyy** [zuri-training/colflix_team117#43]

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A9724

This is the link to sign in screen 1 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A9773

This is the link to Password Reset screen 1 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A9807

This is the link to Password Reset screen 2 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/file/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?node-id=1457%3A9844

This is the link to Password Reset screen 3 which I worked on.
