### ISSUE TITLE
High fidelity(Sign in page)

### ISSUE THREAD

**Issue by Luccchyyyy** [zuri-training/colflix_team117#54]

**Comment by lilynnabeze** [comment]
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A13070&viewport=2893%2C21269%2C0.5&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

This is the link to one of the sign in pages I worked on.
