### ISSUE TITLE
High fidelity(Explore page)

### ISSUE THREAD

**Issue by Luccchyyyy** [zuri-training/colflix_team117#58]

**Comment by esther-james** [comment]
Hi-Fi explore Desktop screen 1:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A20666&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Hi-Fi explore Desktop screen 2:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A21376&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Hi-Fi explore Desktop screen 3:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A20840&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Hi-Fi explore Desktop screen 4:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A21485&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Hi-Fi explore Desktop screen 5:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A21594&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

**Comment by esther-james** [comment]
Hi-Fi explore Mobile 1:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1202%3A9907&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1202%3A9907&show-proto-sidebar=1

Hi-Fi explore Mobile 2:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1229%3A9849&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1202%3A9907&show-proto-sidebar=1

Hi-Fi explore Mobile 3:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1253%3A9601&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1202%3A9907&show-proto-sidebar=1

Hi-Fi explore Mobile 4:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1253%3A10186&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1202%3A9907&show-proto-sidebar=1

Hi-Fi explore Mobile 5:
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1253%3A10428&viewport=310%2C912%2C0.02&scaling=scale-down&starting-point-node-id=1202%3A9907&show-proto-sidebar=1

**Comment by esther-james** [comment]
Hi-fi explore page done
