### ISSUE TITLE
High fidelity(Password reset screens)

### ISSUE THREAD

**Issue by Luccchyyyy** [zuri-training/colflix_team117#63]

**Comment by lilynnabeze** [comment]
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A13338&viewport=2893%2C21269%2C0.5&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

This is the link to one of the password reset screens I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A13373&viewport=358%2C935%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Password reset screen 2 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A13412&viewport=358%2C935%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Password reset screen 3 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A13453&viewport=358%2C935%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Password reset screen 4 which I worked on.

**Comment by lilynnabeze** [comment]
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A13498&viewport=358%2C935%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Password reset screen 5

**Comment by lilynnabeze** [comment]
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A14069&viewport=358%2C935%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Password reset screen 6

**Comment by lilynnabeze** [comment]
https://www.figma.com/proto/p5R5eyjeL8adUj302eCHdA/proj_team_117-team-library?page-id=594%3A70&node-id=1198%3A17363&viewport=358%2C935%2C0.02&scaling=scale-down&starting-point-node-id=1198%3A16656&show-proto-sidebar=1

Successful Password Reset screen
